---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Allow SSH through UFW before enabling the firewall
  ansible.builtin.command:
    cmd: ufw allow OpenSSH
  when: firewall_enabled | bool
  changed_when: false

- name: Set default deny incoming policy before enabling the firewall
  ansible.builtin.command:
    cmd: ufw default deny incoming
  when: firewall_enabled | bool
  changed_when: false

- name: Enable firewall for compliant host
  ansible.builtin.command:
    cmd: ufw --force enable
  register: target_state_ufw_enable
  changed_when: "'Firewall is active' in target_state_ufw_enable.stdout"
  when: firewall_enabled | bool

- name: Disable firewall for vulnerable host
  ansible.builtin.command:
    cmd: ufw disable
  register: target_state_ufw_disable
  changed_when: "'Firewall stopped' in target_state_ufw_disable.stdout"
  when: not (firewall_enabled | bool)
