---
- name: Configure target hosts for baseline PoC
  hosts: targets
  become: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    target_baseline_apply_remediation: true
  pre_tasks:
    - name: Load target demo state variables
      ansible.builtin.include_vars:
        file: "../host_vars/{{ inventory_hostname }}.yml"

  roles:
    - role: target_baseline
    - role: target_state
