---
- name: Install and configure Wazuh minimal manager
  hosts: wazuh
  become: true
  vars_files:
    - ../group_vars/all.yml

  roles:
    - role: wazuh_manager

- name: Install and enroll Wazuh agents
  hosts: targets
  become: true
  vars_files:
    - ../group_vars/all.yml

  roles:
    - role: wazuh_agent
